### ISSUE TITLE
Send midi messages (play and bpm)

### ISSUE THREAD

**Issue by jwktje** [nfroidure/midiplayer#2]
Is it possible to send midi messaged to start playback and/or set the BPM within a DAW?

**Comment by nfroidure** [comment]
I had no clue of what a DAW could be before i googled it ;). I made this lib to just play MIDI files so i assume it is not possible without tweaking it a bit.

In the other hand, i'll accept any PR making significant improvement on it.

**Comment by looshi** [comment]
A tempo setter would be great.  I see the routine to set the tempo is here MIDIFileHeader.prototype.getTickResolution.   So, it seems relatively straightforward to pass a custom tempo in one of the initialize functions, for example :  MIDIPlayer.load(file, myTempo ).

However, it's not apparent how to create a setter, e.g. MIDIPlayer.prototype.setTempo()  because the events would all need to be rescheduled.  Would it even be possible to set the tempo while the file is playing ?   Great library by the way!

**Comment by nfroidure** [comment]
The simplest way to do it would probably be to scale every event.playTime occurence within the player but it will be a bit hard since there's a lot of code depending on current time (see performance.now calls). By example, in order to schedule MIDI events, i had to listen for page hides to tweak the playing delay. Also, there is no tests and great chances to break things (my bad).

Maybe that replacing performance.now per a custom function would also do the job.

On the other hand,I think this library should be rewritten using a WebWorker since the web MIDI API is accessible within it but it would be a huge rewrite. It would necessit to break this library into a MIDIScheduler (that would sit in a worker) and a MIDIPlayer listening to/messaging it.

I clearly have no time yet to achieve this but i'm open to PRs and giving access to the repo for anyone that would like to be involved in this rewrite.
